SELECT CONCAT(HoSV, ' ', TenSV) AS HoTen, YEAR(CURDATE()) - YEAR(NgaySinh) AS Tuoi, TenKhoa FROM DMSV 
JOIN DMKhoa ON DMSV.MaKhoa = DMKhoa.MaKhoa WHERE YEAR(CURDATE()) - YEAR(NgaySinh) BETWEEN 20 AND 25;
